<?php
/**
 * Banners phtml file
 */

/** @var Asg_Advertising_Block_Catalog_Banner $block */
$block = $this;

$banners = $this->getBanners();
?>

<style>

    .modalDialog {
        position: fixed;
        font-family: Arial, Helvetica, sans-serif;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        background: #cfcfcf;
        z-index: 99998;
        -webkit-transition: opacity 400ms ease-in;
        -moz-transition: opacity 400ms ease-in;
        transition: opacity 400ms ease-in;
        display: none;
    }

    .modalDialog:target {
        display: block;
        pointer-events: auto;
    }

    .modalDialog > div {
        width: 400px;
        position: relative;
        margin: 10% auto;
        padding: 0 0 35px 0;
        background: #fff;
    }

    .modalHead {
        background: #f15d5e;
        text-align: center;
        position: relative;
        height: 140px;
    }

    .modalHead h2 {
        position: absolute;
        top: 50%;
        width: 100%;
        margin: 0;
        text-align: center;
        margin-top: -15px;
        font-size: 16px;
        color: #FFFFFF;
    }

    .modalHead:after  {
        content: "";
        width: 0;
        height: 0;
        border-style: solid;
        border-width: 20px 200px 0 200px;
        left: 0;
        bottom: -20px;
        border-color: #f15d5e transparent transparent transparent;
        position: absolute;
    }

    .close {
        background: #f15d5e;
        color: #FFFFFF;
        line-height: 33px;
        position: absolute;
        right: -12px;
        text-align: center;
        top: -10px;
        width: 33px;
        text-decoration: none;
        font-weight: bold;
        border-radius: 30px;
        z-index: 99999;
    }

    .modalBody {
        margin-top: 40px;
        padding-left: 40px;
        font-size: 14px;
        padding-right: 40px;
    }

    .modalBody .btn {
        color: #fff!important;
        background: #f15d5e;
        font-size: 18px;
        display: block;
        text-align: center;
        line-height: 40px;
    }

    .close:hover, .modalBody .btn:hover {
        border: 1px solid #f15d5e;
        background: #FFF; color: #f15d5e;
        cursor: pointer;
    }
</style>


<div class="asg-advertising-banner-grid-data">

    <?php foreach ($banners as $banner):?>

        <div id="advertising-catalog-banner-<?php echo  $banner['id'];?>">
            <img src="<?php echo $banner['banner_grid_data']?>"
                 width="200px"
                data-title="<?php echo $this->escapeHtml($banner['option_title']);?>"
                data-content="<?php echo $this->escapeHtml($banner['content']);?>"
                data-position="<?php echo $this->escapeHtml($banner['grid_position']);?>"
            >
        </div>

    <?php endforeach;?>
</div>


<a id=".show-modal-btn" href="#openModal">Открыть модальное окно</a>

<div id="openModal" class="modalDialog">
    <div class="modalContent">

        <a href="#close" title="Закрыть" class="close">X</a>

        <div class="modalHead">
            <h2>Модальное окно</h2>
        </div>

        <div class="modalBody">
            <p>Прмер простого модального окна, которое может быть создано с использованием CSS3.</p>
            <p>Его можно использовать в широком диапазоне, начиная о т вывода сообщений и заканчивая формой регистрации.</p>
            <p>Прмер простого модального окна, которое может быть создано с использованием CSS3.</p>
            <p>Его можно использовать в широком диапазоне, начиная от вывода сообщений и заканчивая формой регистрации.</p>

            <span class="btn">ПЕРЕЙТИ</span>

        </div>

    </div>
</div>
